version: "3"

services:
  app:
    build: 
      context: .
    container_name: react-app
    ports: 
        - 3000:3000      
    volumes:
      - .:/src/
    image: app:react
    command: npm start