version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 14
    commands:
      - echo "Intalling dependencies ..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building react project ..."
      - npm run build
  post_build: 
    commands:
      - echo "Updating files in the s3 bucket"
      - aws s3 sync build/s3://souobbill-demo-app-2021 --delete